import { ref, computed, watch } from "vue";
import { defineStore } from "pinia";
import w001 from "@/assets/imgs/w001.jpg";
import w002 from "@/assets/imgs/w002.jpg";
import w003 from "@/assets/imgs/w003.jpg";
import w004 from "@/assets/imgs/w004.jpg";
import w005 from "@/assets/imgs/w005.jpg";
import w006 from "@/assets/imgs/w006.jpg";
import w007 from "@/assets/imgs/w007.jpg";
import w008 from "@/assets/imgs/w008.jpg";
import w009 from "@/assets/imgs/w009.jpg";
import w010 from "@/assets/imgs/w010.jpg";
import w011 from "@/assets/imgs/w011.jpg";
import w012 from "@/assets/imgs/w012.jpg";
import w013 from "@/assets/imgs/w013.jpg";
import w014 from "@/assets/imgs/w014.jpg";
import w015 from "@/assets/imgs/w015.jpg";
import w016 from "@/assets/imgs/w016.jpg";
import w017 from "@/assets/imgs/w017.jpg";
import w018 from "@/assets/imgs/w018.jpg";
import w019 from "@/assets/imgs/w019.jpg";
import w020 from "@/assets/imgs/w020.jpg";

export const useProductionStore = defineStore("productions", () => {
  const productions = ref([
    {
      id: 1,
      order: "",
      img: w001,
      title: "燈芯絨水手帽",
      category: "hat",
      star: "★★★★",
      stars: 4,
      price: 1200,
      description:
        "粗條燈芯絨；主題繡花，為今年聖誕設計的幾何小圖；男女皆可戴。",
      color: "orange",
      label: "Other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 2,
      order: "",
      img: w002,
      title: "Puma Suede Classic",
      category: "shoes",
      star: "★★★★★",
      stars: 5,
      price: 3000,
      description: "Puma經典款；低筒；麂皮材質復古",
      color: "black",
      label: "Puma",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 3,
      order: "",
      img: w003,
      title: "Champion AS拼色運動外套(綠色)",
      category: "clothes",
      star: "★★★",
      stars: 3,
      price: 2100,
      description: "Puma經典款；低筒；麂皮材質復古",
      color: "green",
      label: "Champion",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 4,
      order: "",
      img: w004,
      title: "Vans old skool",
      category: "shoes",
      star: "★★★★★",
      stars: 5,
      price: 3200,
      description: "Vans經典不敗款",
      color: "black",
      label: "vans",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 5,
      order: "",
      img: w005,
      title: "STOCK CUFF BEANIE",
      category: "hat",
      star: "★★★★",
      stars: 4,
      price: 1000,
      description: "羅紋結構、輕量材質、電鏽LOGO，100%壓克力纖維",
      color: "black",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 6,
      order: "",
      img: w006,
      title: "BIG LOGO LOW PRO CAP",
      category: "hat",
      star: "★★★★",
      stars: 4,
      price: 1300,
      description: "可調肘節調節器、EVA軟遮陽板，70％尼龍/ 30％棉",
      color: "blue",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 7,
      order: "",
      img: w007,
      title: "Champion AS復古拼色外套",
      category: "clothes",
      star: "★★★",
      stars: 3,
      price: 2500,
      description: "100%滌綸，兩側口袋有拉鍊",
      color: "blue",
      label: "Champion",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 8,
      order: "",
      img: w008,
      title: "Champion AS運動長褲(黑色)",
      category: "pants",
      star: "★★★",
      stars: 3,
      price: 1900,
      description: "100%尼龍",
      color: "black",
      label: "Champion",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 9,
      order: "",
      img: w009,
      title: "經典嘻哈復古拼接外套",
      category: "clothes",
      star: "★★★★★",
      stars: 5,
      price: 2400,
      description: "兩側口袋、100%尼龍、Oversize",
      color: "purple",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 10,
      order: "",
      img: w010,
      title: "Adidas Superstar",
      category: "shoes",
      star: "★★★★",
      stars: 4,
      price: 3600,
      description: "adidas金典款，採用優質皮革鞋面，柔軟舒適，提供透氣性",
      color: "white",
      label: "adidas",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 11,
      order: "",
      img: w011,
      title: "Nike Air Force 1 '07",
      category: "shoes",
      star: "★★★★★",
      stars: 5,
      price: 3800,
      description:
        "泡棉中底，金屬飾標印有「AF1」字樣，腳尖處採沖孔設計，橡膠鞋底",
      color: "white",
      label: "nike",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 12,
      order: "",
      img: w012,
      title: "8 BALL TEE",
      category: "clothes",
      star: "★★★",
      stars: 3,
      price: 1800,
      description: "正常版型TEE、螺紋領口、印刷LOGO、100%棉質",
      color: "black",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 13,
      order: "",
      img: w013,
      title: "TRIBAL MASK TEE",
      category: "clothes",
      star: "★★★",
      stars: 3,
      price: 1700,
      description: "正常版型TEE、螺紋領口、印刷LOGO、100%棉質",
      color: "black",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 14,
      order: "",
      img: w014,
      title: "Champion AS拼色運動長褲",
      category: "clothes",
      star: "★★★★★",
      stars: 5,
      price: 2400,
      description: "100%尼龍",
      color: "black",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 15,
      order: "",
      img: w015,
      title: "Champion 棒球外套",
      category: "clothes",
      star: "★★★★★",
      stars: 5,
      price: 3000,
      description:
        "Nylon Washer外層；100%尼龍；襯裡:100%聚酯纖維；羅紋: 98%聚酯纖維 2%聚氨酯",
      color: "green",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 16,
      order: "",
      img: w016,
      title: "CLASSIC COACH JACKET",
      category: "clothes",
      star: "★★★",
      stars: 3,
      price: 2100,
      description:
        "尖角衣領、彈性伸縮袖口、全鈕扣式開襟、正面斜口袋、腰部可調式拉繩",
      color: "blue",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 17,
      order: "",
      img: w017,
      title: "PANEL TRACK PANT",
      category: "pants",
      star: "★★★★★",
      stars: 5,
      price: 1700,
      description: "正常版型運動褲、可調式抽繩、100%尼龍",
      color: "blue",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 18,
      order: "",
      img: w018,
      title: "格紋寬褲",
      category: "pants",
      star: "★★★★★",
      stars: 5,
      price: 1000,
      description: "兩側口袋、上寬下窄",
      color: "blue",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 19,
      order: "",
      img: w019,
      title: "Miki discovery 網眼拼接水兵帽",
      category: "hat",
      star: "★★★★",
      stars: 4,
      price: 1100,
      description:
        "經典Miki水兵帽版型；純棉材質，局部網眼拼接設計，背部調節帶為皮革；側邊logo刺繡",
      color: "brown",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
    {
      id: 20,
      order: "",
      img: w020,
      title: "STOCK BUCKET HAT",
      category: "hat",
      star: "★★★★",
      stars: 4,
      price: 1200,
      description: "Stussy經典漁夫帽，Basic Stock標誌刺繡",
      color: "black",
      label: "other",
      counter: 1,
      size: "M",
      kupeng: false,
      email: "",
      name: "",
      telphone: "",
      adress: "",
      message: "",
      d: "",
      year: "",
      month: "",
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
      pay: false,
      complete: false,
    },
  ]);

  // 搜尋關鍵字的 ref 變數
  const searchTerm = ref("");

  // 透過 computed 屬性，建立一個搜尋後的商品列表
  const searchedProductionTitle = computed(() => {
    // 如果搜尋關鍵字為空，則回傳全部商品列表
    if (searchTerm.value === "") {
      return productions.value;
    } else if (searchTerm.value === "hat") {
      // 如果搜尋關鍵字為特定商品類別，則回傳該類別的商品列表
      return productions.value.filter((production) => {
        return production.category == searchTerm.value;
      });
    } else if (searchTerm.value === "shoes") {
      return productions.value.filter((production) => {
        return production.category == searchTerm.value;
      });
    } else if (searchTerm.value === "clothes") {
      return productions.value.filter((production) => {
        return production.category == searchTerm.value;
      });
    } else if (searchTerm.value === "pants") {
      return productions.value.filter((production) => {
        return production.category == searchTerm.value;
      });
    } else {
      // 其他情況，回傳包含搜尋關鍵字的商品列表
      return productions.value.filter((production) => {
        return production.title.includes(searchTerm.value);
      });
    }
  });

  return {
    productions,
    searchTerm,
    searchedProductionTitle,
  };
});
